### ISSUE TITLE
Vuestic inside Laravel project

### ISSUE THREAD

**Issue by 33sKamal** [epicmaxco/vuestic-admin#26]
Hello all,
is there any way to migrate this one inside an laravel project.
thanks

**Comment by athiffau** [comment]
I would be interested in this as well.  I spent a bunch of time trying to make this work but not successful yet.  Laravel 5.3 project.

**Comment by someburner** [comment]
I'm sort of doing this myself actually, except I'm not using laravel verbatim, I'm using [apiato](https://github.com/apiato/apiato) for the server and have converted vuestic into an electron package.
To serve it via laravel would be rather painful IMO. Here's my take:

On the one hand Laravel is nice because it manages so much for you, but there are issues with that. I'm new to laravel, but as I understand it the only practical way to do this, in a way that is seamless with laravel, is to use blade templating, like [this](https://murze.be/2017/06/building-realtime-dashboard-powered-laravel-vue-2017-edition/). Laravel makes it sound like it's easy, but personally I don't like the idea of PHP templating inside what would otherwise be a purely Vue/JS project. Now you need to reconcile updates to vue *and* laravel *and* blade. 

Hence my approach of using apiato as the "laravel" side. Then you just using normal REST APIs to get your data and your project can more easily be used if Laravel goes by the wayside or you want to use a different backend.

**Comment by 33sKamal** [comment]
okey so there is no  way for now to have vue-cli applications inside laravel project

**Comment by smartapant** [comment]
@someburner yep, it's better to use admin as a frontend app that consumes json api. I personally don't like to mix any templating with framework's templates

**Comment by mansouryaacoubi** [comment]
what about this? [Vuestic-Laravel](https://github.com/depwaswho/vuestic-laravel)
