### ISSUE TITLE
Colors refactor

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#365]
* For the most part your interest lies within `src\vuestic-theme\vuestic-sass\resources\_variables.scss`.

- [x] Create a list in this ticket for all sections of variables (Layout, Auth etc) to track progress.
  Separate

For each item in the list
- [x] Check duplicate colors and unused colors.
- [x] Move variables to specific component style block.
- [x] This task system wide - so be sure to report any suspicious findings in styles or components.

**Comment by nastassiadanilova** [comment]
list of vars, which have been changed

removed
$violet: #db76df;
$on-focus-background-color: rgba(187, 180, 178, 0.71);

// Layout //
removed
$content-wrap-pr: $layout-padding-right;
$content-wrap-pt: $layout-padding;

//Mobile Layout
removed
$layout-mobile-padding-right: .375rem;
$content-mobile-wrap-margin: 1.125rem;
$content-mobile-wrap-pt: 2rem;
$content-mobile-wrap-pt-fixed-layout: 7rem;

move to ./vuestic-theme/vuestic-components/vuestic-navbar/VuesticNavbar.vue
$nav-mobile-padding-h: .875rem;
$nav-mobile-pt: 1.75rem;
$nav-mobile-pb: 0.5rem;
$nav-mobile-brand-width: 4rem;
$nav-mobile-brand-top: .875rem;
$nav-mobile-brand-left: calc(50% - #{$nav-mobile-brand-width});
$droppdown-mobile-mp: 1.9375rem; removed
$dropdown-mobile-show-b: 2rem;

//Navbar
moved to vuestic-theme/vuestic-components/vuestic-navbar/VuesticNavbar.vue
$navbar-dd-item-height: 48px;

//Breadcrumbs
vuestic-theme/vuestic-components/vuestic-breadcrumbs/VuesticBreadcrumbs.vue
$breadcrumbs-height: 54px;
$breadcrumbs-arrow-font: 0.7rem;
$breadcrumbs-arrow-content: "\f054";

//Sidebar
$sidebar-box-shadow: 0px 8px 14.72px 1.28px rgba(#65a977, 0.3); strange color not in vars list

//Widgets
$widget-box-shadow: 0px 4px 70px -18px rgba(112, 112, 112, 1); not hex color. changed to hex but WITHOUT VAR
removed
$widget-viewport-height: $sidebar-viewport-height;
$widget-body-no-header-height: 100%;
$widget-body-with-header-height: calc(100% - #{$widget-header-height});

//Buttons
removed
$input-btn-border-width: 0px;
$btn-dark-color: $white;
$btn-dark-bg: $darkest-gray;
$btn-dark-border: $darkest-gray;
$btn-pale-bg: $theme-pale;
$btn-pale-color: $white;

//Dropdowns
removed
$dropdown-link-color: $white;
$dropdown-link-color: $white;
$dropdown-link-hover-color: $white;
$dropdown-link-hover-bg: $almost-black;
$dropdown-link-active-color: $white;
$dropdown-link-active-bg: $almost-black;
$dropdown-item-padding-x: 25px;
$dropdown-item-padding-y: 0;
$dropdown-min-width: 15rem;
$dropdown-simple-visible-items: 4;
$dropdown-multi-visible-items: 4;

not move left items because them used in several times in bootstrap-override and nav bar

//Modals
removed
$modal-content-border-width: 0;
$modal-md: 650px;
$modal-lg: 850px;

duplicate vars from dublicate /vuestic-theme/vuestic-components/vuestic-modal/VuesticModal.vue. removed from here.
$modal-header-padding-x: $widget-padding;
$modal-header-padding-y: 0;
$modal-header-height: $widget-header-height;
$modal-header-border: $widget-header-border;
$modal-content-border-radius: 0;
$modal-inner-padding: 25px;
$modal-footer-btns-padding-bottom: 20px;
$modal-footer-btns-margin-x: 10px;

//Forms
removed
$input-border-color: $lighter-gray;
$input-bg-disabled: $white;

moved to vuestic-theme/vuestic-components/vuestic-switch/VuesticSwitch.vue
$vuestic-switch-bg: $brand-primary;
$vuestic-switch-padding: 0.313rem 2.375rem;
$vuestic-switch-border-size: 0.125rem;

//Tables
removed
$table-bg-accent: $white;
$table-border-width: 0;
$state-success-bg: #c8fac6;
$state-danger-bg: #ffcece;
$state-warning-bg: #fff1c8;
$state-info-bg: #dcf1ff;
$table-active-bg: $table-hover-bg;

//Badges
removed
$badge-padding-y: 0.28rem;
$badge-font-size: 0.7rem;
$badge-warning-bg: $theme-orange;
$badge-danger-bg: $theme-red;
$badge-info-bg: $theme-blue;

//Alerts
removed
$alert-padding-x: 1.25rem !default;
$alert-padding-y: .75rem !default;
$alert-margin-bottom: $widget-mb;
$alert-border-radius: 0;
$alert-border-width: 0;

moved to ./vuestic-theme/vuestic-sass/icons/_fonts.scss
//Icons
$bootstrap-sass-asset-helper: false;
$icon-font-name: 'glyphicons-halflings-regular';
$icon-font-svg-id: 'glyphicons_halflingsregular';
$icon-font-path: './fonts/';

//PreLoader
moved to vuestic-theme/vuestic-components/vuestic-layout/VuesticLayout.vue
$vuestic-preloader-left: calc(50% - 140px / 2);
$vuestic-preloader-top: calc(50% - 104px / 2);

//tooltips
removed
$tooltip-font-size: $font-size-base;
$tooltip-max-width: 200px;
$tooltip-color: $white;
$tooltip-bg: $darkest-gray;
$tooltip-border-radius: $font-size-base * 0.5;
$tooltip-opacity: .9;
$tooltip-padding-y: .5rem;
$tooltip-padding-x: .75rem;
$tooltip-margin: 0;
$tooltip-arrow-width: .8rem;
$tooltip-arrow-height: .4rem;
$tooltip-arrow-color: $tooltip-bg;

// Popovers
removed
$popover-font-size: $font-size-base;
$popover-bg: $tooltip-bg;
$popover-max-width: 400px;
$popover-border-width: 0;
$popover-border-color: transparent;
$popover-border-radius: $tooltip-border-radius;
$popover-opacity: $tooltip-opacity;
$popover-header-bg: $tooltip-bg;
$popover-header-color: $white;
$popover-header-padding-y: 0;
$popover-header-padding-x: .75rem;
$popover-header-no-icon-padding-x: 0;
$popover-header-font-weight: bold;
$popover-body-color: $white;
$popover-body-padding-x: $popover-header-padding-x;
$popover-body-no-icon-padding-x: $popover-header-no-icon-padding-x;

$popover-arrow-width: 1rem;
$popover-arrow-height: 1rem;
$popover-arrow-color: transparent;
$popover-arrow-outer-color: fade-in($popover-border-color, .05);

// Toasts
removed
$toast-color: $popover-body-color;
$toast-opacity: $popover-opacity;

$toast-bg: $popover-bg; changed to color because popover bg use only here
$toast-border-radius: $popover-border-radius; changed to value because popover border radius used only here
