### ISSUE TITLE
Provide a toned down theme 

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#642]
The [feedback](https://www.reddit.com/r/javascript/comments/cmpumq/free_and_beautiful_vuejs_admin_template/) (please check it!) on reddit was great. But some of the users indicated that the colors are too bright for them.

The idea is to provide a theme that's less bright (@smartapant: more calm) but generally the same. Might be more dull, so enterprise/corporate guys could use it.

You can play with color pickers on https://vuestic.epicmax.co/, then pass @asvae or @smartapant these variables with a couple screenshots.

**Comment by xx13** [comment]
@asvae @smartapant I think the main issue is not about original colours but rather the generated ones: gradients and hover state. My eyes start to hurt when I hover a button as well :D Let's fix that. 

1. Let's make the left 'generated' gradient colours less saturated and resembling the original colour more.

2. Let's fix the hover state by referring to https://xx13.github.io/vuestic_redesign/#colors and making sure that we use `scale-color` rather than `lighten` or `darken`.

Then we can consider having an alternative pastel palette.

**Comment by xx13** [comment]
@asvae @smartapant here is the example. I used a very dark variation of the green colour and (1) the hover is pretty hardcore and (2) gradient is generated in a strange way so the main colour is not here :D:D The basic idea was that the original colour is one of the colours in the gradient and the lighter one with a slight hue shift is being generated.

![updated_color](https://user-images.githubusercontent.com/22664941/63873198-d9b98600-c9c7-11e9-9db8-9874f18ef853.png)

**Comment by smartapant** [comment]
@asvae

**Comment by asvae** [comment]
@xx13 

> the original colour is used as it is and the lighter one with a slight hue shift is being generated
What you're saying doesn't correspond to zeplin colors (which was the source material for color models): https://app.zeplin.io/project/5bcd9657767a220982a4ab61/screen/5bd8629215d2791b64732487

I think correct way of actions would be to fix zeplin, then to update solution in code.

**Comment by xx13** [comment]
@asvae @smartapant 
### Colours, Gradients, Zeplin
Current version has gradients that consist of 2 colours: an original one and a modified version. That works for all main colours, except for the green (oops).

### Two Green Colours
For some reason green gradient has a slightly different green shade on the right, and I think that caused some confusion about the way gradients should be built though there are no drastic visual differences. Instead of `#40e583` colour #`23e066` was used.
![two_shades](https://user-images.githubusercontent.com/22664941/64702352-059e3680-d4b3-11e9-9992-817c14075de0.png)

### One Green To Rule Them All
Let’s use `#23e066 `as the main green colour. It adds a little more contrast that will be appreciated by users. Here are some examples of this minor update:
![examples](https://user-images.githubusercontent.com/22664941/64702378-151d7f80-d4b3-11e9-8875-27e61f29934a.png)

**If it works for you, I will updated all styles with the green in Zeplin.**

### Gradients
Let’s stick to the following structure: a modified colour on the left and the original colour on the right. Here are some examples:
![gradient_structure](https://user-images.githubusercontent.com/22664941/64702420-2b2b4000-d4b3-11e9-8f2a-cffcfcdde700.png)

Current implementation needs a fix because both colours are modified and the original colour barely impacts the way the gradient will look like.
![gradient_issue](https://user-images.githubusercontent.com/22664941/64702428-341c1180-d4b3-11e9-8315-135f45bbfbcc.png)

### Hover
Let’s fix hover effect. I believe the issue is about using absolute `lighten` values instead of relative ones. That might be the reason why the hover effect looks so rough. Let’s be sure to use `scale-color` instead. I'm good to go with any other solution as long as it solves the issue. Please compare:
![hover_and_pressed](https://user-images.githubusercontent.com/22664941/64702510-5ca40b80-d4b3-11e9-81a5-fa83428a4a89.png)

**Comment by xx13** [comment]
@smartapant @asvae please review the updated scheme. I made shadows smaller so the themes have more differences (but I also have a screen with the same shadows). It will be pretty cool to have different basic colors, but not sure whether we can pull that out keeping in mind variables that we defined (not have updated blue, green, yellow but rather purple, blue, red). Please feel free to comment :)

![dashboard - alt scheme w shadows.png](https://images.zenhubusercontent.com/5af0455b4b5806bc2bd208f1/15034211-e391-4509-9109-041ee642d4a8)

**Comment by smartapant** [comment]
@xx13 looks much calmer now.
What do you think of:
1) Making top-left logo calmer too (green gradient might be no good)
2) paler primary color
3) play with sidebar/navbar colors? (shades of gray instead of blue?)

**Comment by xx13** [comment]
@smartapant 
1. it isn't a big deal as another logotypes will be used there :)
2. kk
3. I tried dark grey colours and then decided to go with something colorful. I'll explore grey options.

**Comment by smartapant** [comment]
@xx13 
1. for demo purposes :D
3. have you also tried white (like widgets)?

**Comment by xx13** [comment]
@smartapant 
yep, I tried lots of different stuff :) I'd show all different options then.

**Comment by xx13** [comment]
@smartapant here are some options, we can combine them to pick an accent colour you like
![dashboard - white.png](https://images.zenhubusercontent.com/5af0455b4b5806bc2bd208f1/33d47dc4-1693-451f-aed7-414711ec162d)![dashboard - dark.png](https://images.zenhubusercontent.com/5af0455b4b5806bc2bd208f1/84037c15-400f-434d-92c1-21ef8ca07564)![dashboard - mix.png](https://images.zenhubusercontent.com/5af0455b4b5806bc2bd208f1/3a651f8d-4d6a-419a-ac7e-f552ac6cc66c)

**Comment by asvae** [comment]
Buttons moved to https://github.com/epicmaxco/vuestic-ui/issues/28

**Comment by xx13** [comment]
![dashboard - alternative theme](https://user-images.githubusercontent.com/22664941/65815828-9768ac00-e1f4-11e9-8f80-cb1475069a4a.png)

@asvae @smartapant please review the updated alternative theme:

Update Log:
* Shadows became smaller and lighter (buttons, cards).
* Main buttons don’t have gradients rather solid colors.
* Updated colors.
* Theme switcher added to the color management tool (top bar). Recover defaults button becomes active if any changes to the themes occur.
* Alternative theme has a different set of default colors with a single accent color.
* Top bar has a shadow.


Updated Colors: 
* primary #6E85E8
* success #8FDB8B
* info #74BBFF
* error #F67170
* warning #FFD55E
* black #34495E
* secondary #8396A5

The screen was uploaded to Zeplin and can be found by 'Dashboard' tag.

**Comment by asvae** [comment]
@xx13 looks great!
