### ISSUE TITLE
Is there a simplified template which is suitable for developing directly?

### ISSUE THREAD

**Issue by YY-GX** [epicmaxco/vuestic-admin#759]
Hi, thank you for developing this wonderful project!

But is there a simplified version which I can directly work on? Because now I have to delete many things from the project every time I use it. Thanks!

**Comment by asvae** [comment]
Hey.

Right now we're working on [vuestic-ui](https://github.com/epicmaxco/vuestic-ui), which is component library, but it's not ready yet.

Can you tell me some examples of what is not useful in vuestic-admin? Right now my idea is that it should be feature packed, then you just directly delete or modify things you need to.

Thanks.

**Comment by The-chosen** [comment]
Thanks for replying. I think a feature packed one is good, but it's better to be viewed as a reference when developing instead of a starter. 

I know I can delete things I don't need, but it's still troublesome when I start my own web app. If there's another version with empty sidebar and clear navigation bar, it may be better.
